### ISSUE TITLE
As a TA, I want to be able to view all the lessons that I have created records for.

### ISSUE THREAD

**Issue by sc-arecrow** [AY2021S1-CS2103-F09-1/tp#75] opened 2020-10-16 06:15 UTC
**Describe the solution you'd like**
* A list of Sessions in Taskmaster
* The TA can switch between his Sessions and view the list of StudentRecords for each of his Sessions

**Comment by joshuacjx** [comment] 2020-10-27 07:52
Duplicate of #97.

**Closed as completed by joshuacjx** 2020-10-27 07:52 UTC
